version: "3.8"

services:
  # ---------------------------------
  # database
  # ---------------------------------
  db:
    image: mysql/mysql-server:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: secret
      # MYSQL_DATABASE: sqlalchemy # DBの作成はdocker/setup.dev.sqlにまとめた
    volumes:
      - db-data80:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - shared-network
      - default

  # ---------------------------------
  # user-api
  # ---------------------------------
  user-api:
    restart: "no"
    tty: true
    build:
      context: ${USER_API_CONTEXT}
      dockerfile: docker/local/python/Dockerfile
    depends_on:
      - db
    ports:
      - "127.0.0.1:9000:9000" # デバッグ用
      - "127.0.0.1:8000:8000" # webサーバー
    volumes:
      - ${USER_API_CONTEXT}:/project
      - ${DATABASE_CONTEXT}:/project/common/database
      - ${MIGRATION_CONTEXT}:/project/migrations # common/migrationsにマウントはできない (SQLAlchemyのmigrateが動かない)
    networks:
      - shared-network
      - default

volumes:
  db-data80:

networks:
  shared-network:
    name: ${PROJECT_NAME}-network
