"""comment

Revision ID: 4d5d471d45c8
Revises: 
Create Date: 2024-04-02 07:42:03.766537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5d471d45c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False, comment='商品コード'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='商品名'),
    sa.Column('unit_price', sa.BigInteger(), nullable=False, comment='単価'),
    sa.Column('percent_tax', sa.String(length=255), nullable=False, comment='消費税率'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名前'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='パスワード'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_code', sa.String(length=10), nullable=False),
    sa.Column('user_address1', sa.String(length=255), nullable=False),
    sa.Column('user_address2', sa.String(length=255), nullable=False),
    sa.Column('user_tel', sa.String(length=15), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('shipping_post_code', sa.String(length=10), nullable=False),
    sa.Column('shipping_user_address1', sa.String(length=255), nullable=False),
    sa.Column('shipping_user_address2', sa.String(length=255), nullable=False),
    sa.Column('shipping_user_tel', sa.String(length=15), nullable=False),
    sa.Column('shipping_user_email', sa.String(length=255), nullable=False),
    sa.Column('shipping_user_name', sa.String(length=255), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('payment_dated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('order_details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_unit_price', sa.BigInteger(), nullable=False),
    sa.Column('product_percent_tax', sa.String(length=255), nullable=False),
    sa.Column('purchase_number', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
